# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankuai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fengmian', models.ImageField(upload_to='bankuai_img')),
                ('name', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=400)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fengmian', models.ImageField(upload_to='blog_img')),
                ('yuedu', models.IntegerField(default=0)),
                ('content', models.TextField(max_length=10000)),
                ('pub_date', models.DateTimeField()),
                ('bankuai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Bankuai')),
            ],
        ),
        migrations.CreateModel(
            name='Leixing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Pinglun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('pltext', models.CharField(max_length=1000)),
                ('plblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
                ('plzhe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='leixing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Leixing'),
        ),
        migrations.AddField(
            model_name='blog',
            name='zuozhe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
