# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170925_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='kuaizhuao',
            field=models.TextField(default=django.utils.timezone.now, max_length=70000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=100000),
        ),
    ]
