# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170925_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='kuaizhuao',
            new_name='kuaizhao',
        ),
    ]
