# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170925_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=3000000),
        ),
    ]
